security:
    password_hashers:
        App\Entity\User:
            algorithm: bcrypt
            cost: 4

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        refresh:
            pattern: ^/api/token/refresh
            stateless: true
            refresh_jwt: ~
        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/users/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/trajets, roles: PUBLIC_ACCESS }
        - { path: ^/api/(login|token/refresh), roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
